# Generated by Django 5.1.7 on 2025-04-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
        ('movies', '0003_rename_favoritemovie_like_alter_like_options_and_more'),
    ]

    operations = [
    ]
